# Site settings
title: Mackenzie Kathyrn Walker
email: rettwalker@email.com
description: > # this means to ignore newlines until "baseurl:"
  It is a baby girl!!!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mackenziewalker.github.io" # the base hostname & protocol for your site
name: Rett Walker


# Build settings
markdown: kramdown
permalink: pretty